### ISSUE TITLE
希望up主给个online表和acitiviti关联图文demo

### ISSUE THREAD

**Issue by hxinqi** [polarbear567/jeecg-boot-activiti-online#2]
startMultiProcess,提示找不到资源，表单组件已写上，bpm_status和act_status,字段均已经加上，但是在线表单点提交流程，找不到资源

**Comment by polarbear567** [comment]
@hxinqi 现在可能没有时间，有空会考虑加下的，感谢建议。

**Comment by hxinqi** [comment]
哈哈，好的，谢谢大神回复

**Comment by polarbear567** [comment]
Hi @hxinqi ,
请参考https://github.com/polarbear567/jeecg-boot-activiti-online#demo
抱歉隔了这么久才把demo写出来哈，如果还有问题请提issue。
