### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Unknown column 'create_time' in 'order clause'

### ISSUE THREAD

**Issue by LiangYongAI** [polarbear567/jeecg-boot-activiti-online#6]
@polarbear567  这个仓库确实集成了activiti，也调通了，但是在用jeecg-boot原本的online表格设计页面时，会报如下错误。

2022-07-18 08:52:00.279 [http-nio-8080-exec-9] ERROR druid.sql.Statement:149 - {conn-10005, pstmt-20045} execute error. SELECT  id,title,text  FROM safety_regulations_data 
  ORDER BY create_time DESC LIMIT ?
java.sql.SQLSyntaxErrorException: Unknown column 'create_time' in 'order clause'

我设计的表格里并没有create_time这个字段，大概猜测create_time是为了集成activiti才引入的，在一般的表格设计里并不需要，怎么改才能兼容还在摸索，先提个issue

**Comment by LiangYongAI** [comment]
补充一下，https://github.com/happy-panda/jeecg-boot-activiti这个仓库也有类似的问题。

**Comment by polarbear567** [comment]
Hi @LiangYongAI 
create_time是原来就有的，你可以看下原版jeecg-boot自己生成的那些表，应该默认都有create_time这个字段的，我自己试了下，默认也是有这个字段的:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/14308067/179436393-ea726f65-35ea-4219-8296-a004b697b3ec.png">
这个safety_regulations_data表是你自己新建的吗？
不太清楚是你手动删除的吗？

**Comment by LiangYongAI** [comment]
是我自己直接从数据库里导入的已有的表，看了教程，确实有几个字段是必须的。
![image](https://user-images.githubusercontent.com/15886620/179438523-8f69d938-2923-426d-90f3-310b334dc926.png)
