### ISSUE TITLE
用online表单申请流程后，删除失败

### ISSUE THREAD

**Issue by LiangYongAI** [polarbear567/jeecg-boot-activiti-online#7]
不用activiti提供的申请走流程，而是用online生成的表单走申请流程，流程被审批后，但删除时失败报下面错误：
“删除失败,该记录有对应的流程没有完成,请完成流程后删除,或将流程撤回草稿状态后删除”
如下图：
<img width="805" alt="1663320432154" src="https://user-images.githubusercontent.com/15886620/190605507-9b677917-29ee-45b7-8e2d-b4bf9a5d9060.png">

**Comment by polarbear567** [comment]
没有足够的信息来进行判断，你能提供错误log吗？
下面这段是删除时候的检测:
https://github.com/polarbear567/jeecg-boot-activiti-online/blob/master/jeecg-boot/jeecg-boot-module-activiti/src/main/java/org/jeecg/activiti/util/ActHelpUtil.java
你能对应这段code查看下你的数据库中的数据吗？

**Comment by LiangYongAI** [comment]
我又试了下，在新建表单后，还没有提交流程时是可以删除这条申请的，但提交流程后以及后面审批后就不可以删除了，我在想，这个问题是不是合理的，流程提交后系统本来就要留记录，不能随意删除？

**Comment by polarbear567** [comment]
时间太长我不记得原因了，似乎是因为直接删除会导致一些bug，可能是流程上的bug，所以我加了这个限制，你可以先撤回再删除
